# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2019 Axway Software SA and its affiliates. All rights reserved.
#
before_script:
- eval export DOCKER_TAG=$CI_COMMIT_REF_NAME
- | # If we're on the master branch, tag the image as latest
  if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
    eval export DOCKER_TAG="latest"
  fi
- echo Using DOCKER_TAG=$DOCKER_TAG

stages:
- build
- test
- security
- push

build-backend:
  stage: build
  script:
  - cd backend; docker build -t st/backend:$DOCKER_TAG .; cd ..

build-edge:
  stage: build
  script:
  - cd edge; docker build -t st/edge:$DOCKER_TAG .; cd ..

test-backend:
  stage: test
  script:
  - cd backend
  - docker-compose -f docker-compose.test.yml down -v
  - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --remove-orphans --force-recreate sut
  after_script:
  - cd backend
  - docker-compose -f docker-compose.test.yml down -v

test-edge:
  stage: test
  script:
  - cd edge
  - docker-compose -f docker-compose.test.yml down -v
  - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --remove-orphans --force-recreate sut
  after_script:
  - cd edge
  - docker-compose -f docker-compose.test.yml down -v

security-backend:
  stage: security
  script:
  # Scan the image and store the URL of the scan results
  - eval export URL=$(twistcli images scan -u $TWISTLOCK_USER -p "$TWISTLOCK_PASSWORD" --address $TWISTLOCK_URL --upload st/backend:$DOCKER_TAG | grep scan | cut -b29-)
  - echo URL=$URL
  # Prepare Twistlock credentials
  - TOKEN=$(echo -n "$TWISTLOCK_USER:$TWISTLOCK_PASSWORD" | openssl base64)
  # Download and untar scan results. Scan results file is "analysis.json"
  - "curl -k -H \"Authorization: Basic $TOKEN\" $URL | tar xvz"
  # Upload to theadfix
  - cat analysis.json | jq .
  # Remove scan results.
  - rm -f analysis.json

security-edge:
  stage: security
  script:
  # Scan the image and store the URL of the scan results
  - eval export URL=$(twistcli images scan -u $TWISTLOCK_USER -p "$TWISTLOCK_PASSWORD" --address $TWISTLOCK_URL --upload st/edge:$DOCKER_TAG | grep scan | cut -b29-)
  - echo URL=$URL
  # Prepare Twistlock credentials
  - TOKEN=$(echo -n "$TWISTLOCK_USER:$TWISTLOCK_PASSWORD" | openssl base64)
  # Download and untar scan results. Scan results file is "analysis.json"
  - "curl -k -H \"Authorization: Basic $TOKEN\" $URL | tar xvz"
  # Upload to theadfix
  - cat analysis.json | jq .
  # Remove scan results.
  - rm -f analysis.json

push-backend:
  stage: push
  script:
  - docker tag st/backend:$DOCKER_TAG $REGISTRY_URL/st/backend:$DOCKER_TAG
  - docker push $REGISTRY_URL/st/backend:$DOCKER_TAG

push-edge:
  stage: push
  script:
  - docker tag st/edge:$DOCKER_TAG $REGISTRY_URL/st/edge:$DOCKER_TAG
  - docker push $REGISTRY_URL/st/edge:$DOCKER_TAG
