version: "3.4"
services:
  st-backend:
    image: st-backend
    build: .
    environment:
      ST_CORE_LICENSE: cat /run/secrets/st-core-license
      ST_FEATURE_LICENSE: cat /run/secrets/st-feature-license
    secrets:
      - st-core-license 
      - st-feature-license
    ports:
    - "9444:444"     # ADMIN
    - "9021:21"      # FTP
    - "9080:80"      # HTTP
    - "9443:443"     # HTTPS
    - "9022:22"      # SFTP
    - "17617:17617"  # PESIT-TCP
    - "17627:17627"  # PESIT-TCP-SSL
    - "19617:19617"  # PESIT-pTCP
    - "19627:19627"  # PESIT-pTCP-SSL

secrets:
  st-core-license:
    file: ../../licenses/st-core-license.txt
  st-feature-license:
    file: ../../licenses/st-feature-license.txt

