version: "3.4"
services:
  st-edge:
    image: axway-docker-ci.bintray.io/st/edge
    environment:
      ST_CORE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-core-license.txt"
      ST_FEATURE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-feature-license.txt"
      ST_GLOBAL_CONFIG_PATH: /run/secrets/st-edge-services-config-file
      ST_CA_PATH: /run/secrets/st-root-ca.crt
      ST_CA_ALIAS: docker_ca
      ST_CERT_PATH: /run/secrets/st-edge-services-crt.p12
      ST_CERT_PASS: SECRET123
      ST_CERT_ALIAS: dockerd
    stop_grace_period: 1m
    secrets:
    - st-edge-services-config-file
    - st-root-ca.crt
    - st-edge-services-crt.p12
    networks:
      streaming:
        aliases:
        - edge.example.com
    ports:
    - "9444:444"     # ADMIN
    - "9021:21"      # FTP
    - "50000:50020"  # Passive FTP Port Range
    - "9080:80"      # HTTP
    - "9443:443"     # HTTPS
    - "9022:22"      # SFTP
    - "10080:10080"  # AS2 HTTP
    - "10443:10443"  # AS2 HTTPs
    - "17617:17617"  # PESIT-TCP
    - "17627:17627"  # PESIT-TCP-SSL
    - "19617:19617"  # PESIT-pTCP
    - "19627:19627"  # PESIT-pTCP-SSL

  st-backend:
    image: axway-docker-ci.bintray.io/st/backend
    environment:
      ST_CORE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-core-license.txt"
      ST_FEATURE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-feature-license.txt"
      ST_GLOBAL_CONFIG_PATH: /run/secrets/st-be-services-config-file
      ST_CA_PATH: /run/secrets/st-root-ca.crt
      ST_CA_ALIAS: docker_ca
      ST_CERT_PATH: /run/secrets/st-be-services-crt.p12
      ST_CERT_PASS: SECRET123
      ST_CERT_ALIAS: dockerd
    stop_grace_period: 1m
    secrets:
    - st-be-services-config-file
    - st-root-ca.crt
    - st-be-services-crt.p12
    networks:
      streaming:
        aliases:
        - backend.example.com
    ports:
    - "10444:444"

networks:
  streaming:
    driver: overlay

secrets:
  st-edge-services-config-file:
    file: edge/runtime/STGlobalConfig.properties
  st-root-ca.crt:
    file: edge/runtime/certs/ST_DOCKER_CA.crt
  st-edge-services-crt.p12:
    file: edge/runtime/certs/ST_EDGE_CERT.p12
  st-be-services-crt.p12:
    file: backend/runtime/certs/ST_BE_CERT.p12
  st-be-services-config-file:
    file: backend/runtime/streaming/STGlobalConfig.properties
