# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2019 Axway Software SA and its affiliates. All rights reserved.
#
version: "3.4"
services:
  st-backend:
    image: st/backend:$DOCKER_TAG
#    command: "sleep"
    environment:
      ST_CORE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-core-license.txt"
      ST_FEATURE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-feature-license.txt"
      ST_GLOBAL_CONFIG_PATH: /run/secrets/st-be-services-config-file
      START_SCRIPTS_CONF_PATH: /run/secrets/st-be-services-jvm-config-file
      SETUP_EXTERNAL_SERVICES_PATH: /run/secrets/st-be-setup-external-services.sh 
      ST_SENTINEL_CONFIG_PATH: "/run/secrets/st-be-sentinel-config-file"
      ST_CA_PATH: /run/secrets/st-root-ca.crt
      ST_CA_ALIAS: docker_ca
      ST_CERT_PATH: /run/secrets/st-be-services-crt.p12
      ST_CERT_PASS: SECRET123
      ST_CERT_ALIAS: dockerd
    stop_grace_period: 2m
    secrets:
    - st-be-services-config-file
    - st-be-setup-external-services.sh
    - st-be-services-jvm-config-file
    - st-be-sentinel-config-file
    - st-root-ca.crt
    - st-be-services-crt.p12
    ports:
    - "9444:444"     # ADMIN
    - "9021:21"      # FTP
    - "9080:80"      # HTTP
    - "9443:443"     # HTTPS
    - "9022:22"      # SFTP
    - "17617:17617"  # PESIT-TCP
    - "17627:17627"  # PESIT-TCP-SSL
    - "19617:19617"  # PESIT-pTCP
    - "19627:19627"  # PESIT-pTCP-SSL

secrets:
  st-be-services-config-file:
    file: runtime/standalone/STGlobalConfig.properties
  st-be-services-jvm-config-file:
    file: runtime/standalone/STStartScriptsConfig
  st-be-setup-external-services.sh:
    file: runtime/setup_external_services.sh
  st-be-sentinel-config-file:
    file: runtime/standalone/SentinelConfig.json
  st-root-ca.crt:
    file: runtime/certs/ST_DOCKER_CA.crt
  st-be-services-crt.p12:
    file: runtime/certs/ST_BE_CERT.p12
