# replace all occurances of <namespace with your namespace
apiVersion: v1
kind: Service
metadata:
  name: haproxy-streaming-service
  namespace: <namespace>
  labels: 
    run: haproxy-streaming
spec:
  type: NodePort
  ports:
    - port: 20080
      targetPort: 20080
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: http-streaming
    - port: 20021
      targetPort: 20021
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-streaming
    - port: 21080
      targetPort: 21080
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: as2-streaming
    - port: 20022
      targetPort: 20022
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ssh-streaming
    - port: 27617
      targetPort: 27617
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: pesit-streaming
    - port: 20444
      targetPort: 20444
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: admin-streaming
    - port: 8404
      targetPort: 8404
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: haproxy-streaming-stats
  selector:
    run: haproxy-streaming
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-streaming
  namespace: <namespace>
  labels:
    run: haproxy-streaming
spec:
  clusterIP: None
  ports:
    - port: 8444
      targetPort: 8444
      protocol: TCP
      name: admin
  selector:
    run: haproxy-streaming
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-streaming
  namespace: <namespace>
  labels:
    k8s-app: haproxy-streaming
    run: haproxy-streaming
spec:
  selector:
    matchLabels:
      run: haproxy-streaming
  template:
    metadata:
      labels:
        run: haproxy-streaming
    spec:
      containers:
      - name: haproxy-streaming
        image: haproxy:latest
        volumeMounts:
        - name: secret-volume
          mountPath: "/usr/local/etc/haproxy/"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: haproxy-streaming-secret