# replace all occurances of <namespace with your namespace
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service 
  namespace: <namespace> #replace me
  labels: 
    run: haproxy
spec:
  type: NodePort
  ports:
    - port: 8444
      targetPort: 8444
      nodePort:  # Add port in range from 30000 - 32767
      protocol: TCP
      name: admin
    - port: 30002
      targetPort: 30002
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp
    - port: 8080
      targetPort: 8080
      nodePort: # Add port in range from 30000 - 32767
      protocol: TCP
      name: http-non-ssl
    - port: 8443
      targetPort: 8443
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: http
    - port: 8022
      targetPort: 8022
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ssh
    - port: 10080
      targetPort: 10080
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: as2-nonssl
    - port: 10443
      targetPort: 10443
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: as2-ssl
    - port: 17617
      targetPort: 17617
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: pesit-nonssl
    - port: 17627
      targetPort: 17627
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: pesit-ssl
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p1
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort: # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p2
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p3
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p4
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p5
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p6
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p7
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p8
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p9
    - port: # same as nodePort port
      targetPort: # same as nodePort port
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: ftp-p10
    - port: 8404
      targetPort: 8404
      nodePort:   # Add port in range from 30000 - 32767
      protocol: TCP
      name: stats
  selector:
    run: haproxy
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: <namespace> #replace me
  labels:
    run: haproxy
spec:
  clusterIP: None
  ports:
    - port: 8444
      targetPort: 8444
      protocol: TCP
      name: admin
  selector:
    run: haproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: <namespace> #replace me
  labels:
    k8s-app: haproxy
    run: haproxy
spec:
  selector:
    matchLabels:
      run: haproxy
  template:
    metadata:
      labels:
        run: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        volumeMounts:
        - name: secret-volume
          mountPath: "/usr/local/etc/haproxy/"
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: haproxy-secret