version: "3.4"
services:
  sut:
    build: ./test
    depends_on:
    - st-edge
    - st-backend
    environment:
      ST_EDGE_HOST: "st-edge"
      ST_BACKEND_ADMIN_UI_URI: "st-backend:444"
  
  st-edge:
    image: st/edge:$DOCKER_TAG
    environment:
      ST_CORE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-core-license.txt"
      ST_FEATURE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-feature-license.txt"
      ST_GLOBAL_CONFIG_PATH: /run/secrets/st-edge-services-config.properties
      ST_NETWORK_ZONES_CONFIG_PATH: /run/secrets/st-edge-network-zone-private.json
      ST_OPTIONS_OVERWRITE_CONF_PATH: /run/secrets/st-edge-options-overwrite.conf
      SETUP_EXTERNAL_SERVICES_PATH: /run/secrets/st-setup-external-services.sh
      ST_CA_PATH: /run/secrets/st-root-ca.crt
      ST_CA_ALIAS: docker_ca
      ST_CERT_PATH: /run/secrets/st-edge-services-crt.p12
      ST_CERT_PASS: SECRET123
      ST_CERT_ALIAS: dockerd
    stop_grace_period: 1m
    secrets:
    - st-edge-services-config.properties
    - st-edge-network-zone-private.json
    - st-edge-options-overwrite.conf
    - st-setup-external-services.sh
    - st-root-ca.crt
    - st-edge-services-crt.p12
    ports:
    - "9444:444"     # ADMIN
    - "9021:21"      # FTP
    - "50000:50020"  # Passive FTP Port Range
    - "9080:80"      # HTTP
    - "9443:443"     # HTTPS
    - "9022:22"      # SFTP
    - "10080:10080"  # AS2 HTTP
    - "10443:10443"  # AS2 HTTPs
    - "17617:17617"  # PESIT-TCP
    - "17627:17627"  # PESIT-TCP-SSL
    - "19617:19617"  # PESIT-pTCP
    - "19627:19627"  # PESIT-pTCP-SSL

  st-backend:
    image: st/backend:$DOCKER_TAG 
    environment:
      ST_CORE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-core-license.txt"
      ST_FEATURE_LICENSE: "curl http://dml.phx.axway.int/licenses/st/st-feature-license.txt"
      ST_GLOBAL_CONFIG_PATH: /run/secrets/st-be-services-config.properties
      ST_NETWORK_ZONES_CONFIG_PATH: /run/secrets/st-be-network-zone-edge.json
      ST_OPTIONS_OVERWRITE_CONF_PATH: /run/secrets/st-be-options-overwrite.conf
      ST_SENTINEL_CONFIG_PATH: /run/secrets/st-be-sentinel-config.json
      SETUP_EXTERNAL_SERVICES_PATH: /run/secrets/st-setup-external-services.sh
      ST_CA_PATH: /run/secrets/st-root-ca.crt
      ST_CA_ALIAS: docker_ca
      ST_CERT_PATH: /run/secrets/st-be-services-crt.p12
      ST_CERT_PASS: SECRET123
      ST_CERT_ALIAS: dockerd
    stop_grace_period: 1m
    secrets:
    - st-be-services-config.properties
    - st-be-network-zone-edge.json
    - st-be-options-overwrite.conf
    - st-be-sentinel-config.json
    - st-setup-external-services.sh
    - st-root-ca.crt
    - st-be-services-crt.p12
    ports:
    - "10444:444"

secrets:
  ### EDGE ###
  st-edge-services-config.properties:
    file: runtime/STGlobalConfig.properties
  st-edge-network-zone-private.json:
    file: runtime/NetworkZonePrivateConfig.json
  st-edge-options-overwrite.conf:
    file: runtime/OptionsOverwrite.conf
  st-setup-external-services.sh:
    file: runtime/setup_external_services.sh
  st-root-ca.crt:
    file: runtime/certs/ST_DOCKER_CA.crt
  st-edge-services-crt.p12:
    file: runtime/certs/ST_EDGE_CERT.p12
  ### BACKEND ###
  st-be-services-crt.p12:
    file: ../backend/runtime/certs/ST_BE_CERT.p12
  st-be-services-config.properties:
    file: ../backend/runtime/streaming/STGlobalConfig.properties
  st-be-network-zone-edge.json:
    file: ../backend/runtime/streaming/NetworkZoneEdgeConfig.json
  st-be-sentinel-config.json:
    file: ../backend/runtime/streaming/SentinelConfig.json
  st-be-options-overwrite.conf:
    file: ../backend/runtime/streaming/OptionsOverwrite.conf

