apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: <namespace> # replace me
  labels:
    run: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: admin
  selector:
    run: mysql
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: mysql
      namespace: <namespace> # replace me
      labels:
        k8s-app: mysql
        run: mysql
    spec:
      selector:
        matchLabels:
          run: mysql
      template:
        metadata:
          labels:
            run: mysql
        spec:
          containers:
          - name: mysql
            image: mysql:5.6.48
            env:
                - name: MYSQL_ROOT_PASSWORD
                  value: "tumbleweed"
            volumeMounts:
                - name: nfs-volume
                  mountPath: /var/lib/mysql
                - name: secret-volume-certificates
                  mountPath: /etc/certs
                - name: secret-volume-config
                  mountPath: /etc/mysql/conf.d
          volumes:
          - name: secret-volume-certificates
            secret:
              secretName: mysql-secret-certificates
          - name: secret-volume-config
            secret:
              secretName: mysql-config
          - name: nfs-volume
            nfs:
              server: <ip-of-nfs-server>
              path: #absolute path on NFS server